# Base image
FROM node
# Make folder to put our files in
RUN mkdir -p /usr/src/app
RUN mkdir -p /usr/src/app/db
# Set working directory so that all subsequent command runs in this folder
WORKDIR /usr/src/app/db
# Copy package json and install dependencies

RUN CREATE TABLE table_sample(timestamp TEXT, description TEXT);

RUN SELECT * from table_sample;
# Copy our app
# COPY . .
# Expose port to access server
EXPOSE 5432
# Command to run our app
#CMD [ "node", "server.js"]

# ENTRYPOINT /bin/bash
